// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode



// paste your JS generated by blockly below here
var result, acronym, mot_couper, item;


result = '';
acronym = window.prompt('enter a phrase');
mot_couper = acronym.split(',');
for (var item_index in mot_couper) {
  item = mot_couper[item_index];
  result += String(item.charAt(0).toUpperCase());
}
window.alert(result);